spongeApiVersion = 7.3.0
nucleusVersion = 2.4.3
# Use RELEASE for a release verison
nucleusVersionSuffix = SNAPSHOT
minecraftversion = 1.12.2

# Maven

groupId = io.github.nucleuspowered
artifactId = nucleus
ghUri = https://maven.pkg.github.com/
ghSlug = NucleusPowered/NucleusRevived

# Deps (moved to local `libs/` directory)

qsmlDep = :quickstart-moduleloader:0.12.1
neutrinoDep = :neutrino:1.1.7

# Descriptive

description = The Ultimate Essentials Plugin for Sponge
url = https://nucleuspowered.org

# The S part of the versioning
declaredApiVersion = 7.3
